FROM node:alpine

RUN apk update && apk upgrade

WORKDIR /usr/src/server

COPY . .

RUN npm install -g yarn
RUN yarn

RUN yarn run build

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

USER node

CMD ["node", "dist/index.js"]
